### ISSUE TITLE
issues whit make hostapd-2.8

### ISSUE THREAD

**Issue by Majedhm1** [arkadeepsen/Handover#1]
hello arkadeepsen:
I am new with linux systems 
when I tray to compiling hostapd-2.8 with make tool,
while compiling an error massege are appear and then the compilation was stopping 
=================================================
the error massege:
make: *** No rule to make target '/home/arkadeep/Softwares/Handover/hostapd-2.8/src/utils/includes.h', needed by '../src/ofSwitchAP/controller_interface.o'.  Stop.
=====================================================
could you help me to complet my thesis and complet the project

**Comment by arkadeepsen** [comment]
Follow the compilation instructions of the individual softwares [here](https://github.com/arkadeepsen/Handover/blob/master/README.md#compilation). The repo contains already compiled files. Those needs to be cleaned first. Then the files can be compiled.

I am closing this issue as all the instructions are already available in the Readme.

**Comment by Majedhm1** [comment]
i am flow the instructios as Readme but to solve the issue, we needed to create full-path as mentioned in the issue above, finally the compilation comleted successfully 
I hope that, help who interesting with this work
